//  Auth - Signup
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//  Auth - Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//  Auth - Logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Skin Products
export const GET_SKIN_PRODUCT = "GET_SKIN_PRODUCT";
export const GET_SKIN_PRODUCT_SUCCESS = "GET_SKIN_PRODUCT_SUCCESS";
export const GET_SKIN_PRODUCT_FAILURE = "GET_SKIN_PRODUCT_FAILURE";

// Hair Products
export const GET_HAIR_PRODUCT = "GET_HAIR_PRODUCT";
export const GET_HAIR_PRODUCT_SUCCESS = "GET_HAIR_PRODUCT_SUCCESS";
export const GET_HAIR_PRODUCT_FAILURE = "GET_HAIR_PRODUCT_FAILURE";

// BathNBody Products
export const GET_BATHNBODY_PRODUCT = "GET_BATHNBODY_PRODUCT";
export const GET_BATHNBODY_PRODUCT_SUCCESS = "GET_BATHNBODY_PRODUCT_SUCCESS";
export const GET_BATHNBODY_PRODUCT_FAILURE = "GET_BATHNBODY_PRODUCT_FAILURE";

// All Products
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

// Single Product
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";


// Cart
export const GET_CART = "GET_CART";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";




export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const INC_CART_QUANTITY = "INC_CART_QUANTITY";
export const DEC_CART_QUANTITY = "DEC_CART_QUANTITY";


// Avatar
export const GET_AVATAR = "GET_AVATAR";
export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS";
export const GET_AVATAR_FAILURE = "GET_AVATAR_FAILURE";
export const POST_AVATAR = "POST_AVATAR";
export const POST_AVATAR_SUCCESS = "POST_AVATAR_SUCCESS";
export const POST_AVATAR_FAILURE = "POST_AVATAR_FAILURE";




// Address
export const POST_ADDRESS = "POST_ADDRESS";
export const POST_ADDRESS_SUCCESS = "POST_ADDRESS_SUCCESS";
export const POST_ADDRESS_FAILURE = "POST_ADDRESS_FAILURE";

export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";





